### ISSUE TITLE
Cannot Resolve 'WebSdk'

### ISSUE THREAD

**Issue by s00179906** [hidglobal/digitalpersona-devices#10] opened 2020-12-05 17:14 UTC
Hi guys im trying to use the 4500 reader on a react application but i am getting this error 

```
Failed to compile.

./node_modules/@digitalpersona/devices/dist/es5.bundles/index.umd.js
Module not found: Can't resolve 'WebSdk' in 'C:\Users\Ibrah\Desktop\virtual-dapp-client\node_modules\@digitalpersona\devices\dist\es5.bundles'```

**Comment by a-bronx** [comment] 2021-01-17 09:29
Duplicate of #4.

**Closed by a-bronx** 2021-01-17 09:29 UTC
